# [package]
# name = "chess"
# version = "0.1.0"
# edition = "2024"

# [dependencies]
# raylib = { version = "5.5" }

[workspace]
resolver = "2"
members  = [
    "crates/board",
    "crates/gui"
]

# TODO: Check integrity function
# No pieces in the same square
